ENV['ELASTICSEARCH_URL'] = ENV['BONSAI_URL'] if ENV['BONSAI_URL']ENV['ELASTICSEARCH_URL'] = ENV['BONSAI_URL'] if ENV['BONSAI_URL']

if ENV['ELASTICSEARCH_URL']
  Tire.configure do
    url ENV['ELASTICSEARCH_URL']
  end
end